name: Ben Fulton-Gillon
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43843
title: Ben Fulton-Gillon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a2b1c4'
    - '#361810'
    - '#fed681'
    - '#747a92'
  brandStrength: 0.23600686015561223
  lightness: 0.3537737997248769
  saturation: 0.3179985957685858
  rhythmicContrast: 0.7877267214935273
purpose: []
