name: Ben Fulton-Gillon
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43843
title: Ben Fulton-Gillon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b49d67'
    - '#978150'
    - '#9c5329'
    - '#6d371b'
    - '#cd7741'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
